# Generated by Django 4.2.18 on 2026-09-28 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('resource_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('raw', 'Raw Document'), ('audio', 'Audio')], default='image', max_length=10)),
                ('format', models.CharField(blank=True, max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('telegram_file_id', models.CharField(max_length=255)),
                ('telegram_message_id', models.BigIntegerField()),
                ('local_thumb_path', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.CharField(default='root', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
